group 'com.air.ai_barcode'
version '1.0-SNAPSHOT'

buildscript {
    ext.kotlin_version = '1.9.22'
    ext.android_gradle_version = '8.7.3'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath "com.android.tools.build:gradle:$android_gradle_version"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    namespace 'com.air.ai_barcode'
    compileSdkVersion 35

    compileOptions {
        // Flag to enable support for the new language APIs

        // Sets Java compatibility to Java 8
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        multiDexEnabled true
        minSdkVersion 21
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

    implementation 'com.journeyapps:zxing-android-embedded:4.3.0'

    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.0.3")
    implementation "androidx.multidex:multidex:2.0.1"
}
